[package]
name = "visitor"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
chrono = "0.4.45"
crossterm = "0.29.0"
dirs = "6.0.0"
libvisitor = { path = "../libvisitor" }
ratatui = "0.30.2"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
